# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    depend_on_referenced_packages: ignore
  exclude:
    - build/**
    - ios/**
    - android/**
    - linux/**
    - macos/**
    - windows/**

linter:
  rules:
    - prefer_const_constructors
    - prefer_final_locals
    - always_use_package_imports
    - avoid_print
    - unnecessary_late
    - unnecessary_parenthesis
    - use_super_parameters
    - prefer_single_quotes

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
